test/make_nm.cpp
test/make_nm_branch.cpp
test/make_nm_fp.cpp
test/make_nm_load_store.cpp
test/make_nm_simd.cpp
test/make_nm_simd_fp_load_store.cpp
test/make_nm_sve.cpp
test/make_nm_sve_addr.cpp
test/meta_mnemonic.cpp
xbyak_aarch64/xbyak_aarch64.h
xbyak_aarch64/xbyak_aarch64_reg.h

`uint64` is defined for a very old compiler in xbyak, so I think that it is better to use standard type `uint64_t` instead of it now.

use uint64_t instead of uint64

---

README.md
sample/add.cpp
sample/label.cpp
test/meta_mnemonic.cpp
test/test_nm.sh
utility/make_reg_class.py
xbyak_aarch64/xbyak_aarch64_adr.h
xbyak_aarch64/xbyak_aarch64_err.h
xbyak_aarch64/xbyak_aarch64_reg.h

XBYAK_AARCH64_OBJ is difficult to handle, so it is better to be removed.

Remove obj macro

---

README.md
xbyak_aarch64/xbyak_aarch64_gen.h

The conversion from a negative value of `double` type to `uint32_t` is undefined behavior, so we should use `int32_t` type.

Fix wrong fmov

---

xbyak_aarch64/xbyak_aarch64_mnemonic.h

setCodeInfo is disabled unless XBYAK_USE_FILE_LINE to reduce compile time.
The time of a tiny test is reduced from 12 sec to 10 sec.

disable setCodeInfo to reduce compile time

---

utility/make_alias_branch.py
xbyak_aarch64/xbyak_aarch64_mnemonic.h

I added aias of SVE cond for vector loop flow.
`b_first(label)` is available instead of `b(MI, label)`.

add alias of sve cond

---

README.md
sample/add.cpp
sample/label.cpp
test/workaround.hpp
xbyak_aarch64/xbyak_aarch64_code_array.h
xbyak_aarch64/xbyak_aarch64_gen.h
xbyak_aarch64/xbyak_aarch64_label.h

- The current the return value of getSize() and the size of AllocatorAArch64::alloca(size) are not byte but uint32_t, so they are misleading.
- `maxSize_` should be the num of uint32_t because it is compared with `size_`.
So I modified as the followings:
- rename `getSize()` to `getUint32Num()` and add `getSize()` which returns byte size.
- change the return type of `getCode()` from `uint32_t*` to `uint8_t*` like as the original xbyak.
- etc.

change meaning of getCode()/getSize()

---

xbyak_aarch64/xbyak_aarch64_code_array.h
xbyak_aarch64/xbyak_aarch64_gen.h

xbyak_aarch64 treats `dw` to write 4-byte data, but it is different from the original behavior and then `dw_aarch64` is necessary for xbyak_translator_aarch64.
So I think that it is better to use `dd` instead of `dw` to write 4-byte data.

use dd instead of dw

---

xbyak_aarch64/xbyak_aarch64_util.h

Old `sys/prctl.h` has no `#define PR_SVE_GET_VL 51`.

workaround for no PR_SVE_GET_VL definition

---

xbyak_aarch64/xbyak_aarch64_gen.h
xbyak_aarch64/xbyak_aarch64_impl.cpp
xbyak_aarch64/xbyak_aarch64_impl.h

This PR enables a partially precompiled header.
The default behavior is the same as the previous one.
```
% time clang++ sample/label.cpp -Ofast -DNDEBUG -I ./
6.938u 0.057s 0:06.99 99.8%     0+0k 0+640io 0pf+0w
```
To use a compiled object, compile `xbyak_aarch64/xbyak_aarch64_impl.cpp` once.
```
clang++ xbyak_aarch64/xbyak_aarch64_impl.cpp -c -I ./ -DNDEBUG -Ofast
```
And compile `sample/label.cpp` with `-DXBYAK_AARCH64_COMPILED` and link `xbyak_aarch64_impl.o`.
```
% time clang++ sample/label.cpp -Ofast -DNDEBUG -I ./ -DXBYAK_AARCH64_COMPILED xbyak_aarch64_impl.o
5.447u 0.037s 0:05.48 99.8%     0+0k 0+896io 0pf+0w
```
I'll increase compiled functions in xbyak_aarch64_impl.cpp.

precompile header

---

Makefile

Without "-std=c++11", gcc 5.4.0 (Ubuntu-16.04) fails to build.

build: add build "-std=c++11" to build option

---

sample/add2.cpp

According to the comments in the code and README, the `ready()` function seems designed to be called after appending a sequence of instructions, before calling `getCode()`.

`ready()` should be after appending codes, before `genCode()`

---

xbyak_aarch64/xbyak_aarch64_err.h

It seems the order of the error messages doesn't match with that of Error enums.

Fix error message array

---

xbyak_aarch64/xbyak_aarch64_util.h

isAtomicSupported() checks for the presence of atomic instructions supported by Armv8.1.

util: add atomic instructions support check

---

xbyak_aarch64/xbyak_aarch64_util.h

On Linux, it seems to be better to use `getauxval` to get the CPU capability, as explained at https://github.com/oneapi-src/oneDNN/issues/1025 .

modify getting method of CPU capability

---

xbyak_aarch64/xbyak_aarch64_util.h

Because older Linux such as Ubuntu 16.04 has no definition of `HWCAP_ATOMICS`, `HWCAP_FP`, `HWCAP_ASIMD` in `<bits/hwcap.h>` which is included from `<sys/auxv.h>`. `<asm/hwcap.h>`, which defines the same `HWCAP_ATOMICS`, `HWCAP_FP`, and `HWCAP_ASIMD`, is used as an alternative.

add <asm/hwcap.h> for Ubuntu 16.04

---

xbyak_aarch64/xbyak_aarch64.h

GCC11 requires including <limits> explicitly.
https://github.com/oneapi-src/oneDNN/issues/1085

fix gcc-11 compile error

---

xbyak_aarch64/xbyak_aarch64_gen.h

`#elif defined` is better than `#elif`

use 'defined' for macro

---

README.md

The link to `sample/protect-re.cpp` is missing. 
Please consider removing the following sentence.
> See [protect-re.cpp](sample/protect-re.cpp).

fix a missing link

---

src/xbyak_aarch64_impl.h

C++ reference should be used for the following case, otherwise `L(Done)` uses a reference to an object that no longer exists.
```C++
Label Done;
cbz(XReg(0), Done);
L(Done);
```

fix cbz/cbnz/tbz/tbnz

---

test/test_all.sh
test/test_integrated.sh

Additional tests for arithmetic and mov to be used in CI.
Addressing https://github.com/fujitsu/xbyak_aarch64/issues/27
Unclear if the codes should be refactored.

Add test for "mov" and "(mov|add|adds|sub|subs)_imm"

---

src/err_impl.h
src/util_impl.cpp
src/xbyak_aarch64_impl.cpp
xbyak_aarch64/xbyak_aarch64.h
xbyak_aarch64/xbyak_aarch64_adr.h
xbyak_aarch64/xbyak_aarch64_code_array.h
xbyak_aarch64/xbyak_aarch64_err.h
xbyak_aarch64/xbyak_aarch64_gen.h
xbyak_aarch64/xbyak_aarch64_label.h
xbyak_aarch64/xbyak_aarch64_util.h

1. move OS-depended code from xbyak_aarch64_util.h to src/util_impl.cpp
2. support macOS
3. `<exception>` should be included from global namespace

Refactor util

---

CMakeLists.txt
README.md
sample/CMakeLists.txt
src/util_impl.cpp
src/xbyak_aarch64_impl.cpp
src/xbyak_aarch64_impl.h
test/CMakeLists.txt
xbyak_aarch64/xbyak_aarch64.h
xbyak_aarch64/xbyak_aarch64_gen.h

This patch can support ARM64 on Windows with Visual Studio.
Some functions in util are not implemented yet, but `sample/add.cpp` runs well.

Support ARM64 Windows

---

xbyak_aarch64/xbyak_aarch64.h

The change is required to fix this compilation error which you can only re-produce with gcc13.

aarch64: fix build warning under gcc13

---

sample/Makefile
sample/perf.cpp
xbyak_aarch64/xbyak_aarch64_perf.h

[The previous PR](https://github.com/fujitsu/xbyak_aarch64/pull/12) was merged into the master but is not included in the latest version for some reason. So I made another PR.
cf. https://github.com/fujitsu/xbyak_aarch64/issues/7

Add Xbyak_aarch64::Profiler for perf command

---

src/util_impl_linux.h

Linux kernel headers used in Ubuntu 20.04 do not define HWCAP2_BF16. To detect BF16 capability in Ubuntu 20.04, HWCAP2_BF16 is defined in Xbyak_aarch64.

[linux] BF16 capability detection for Ubuntu 20.04

---

sample/cpuinfo.FX700.a64fx.centOS.8_3.txt
sample/cpuinfo.JetsonNano.Cortex-A57.ubuntu.18_04.txt
sample/cpuinfo.Mac_mini.M1.macOS.13_5_2.txt
sample/cpuinfo.WindowsDevKit2023.Snapdragon_8cx_Gen3.windows.11.txt
sample/cpuinfo.c7g_medium.Graviton3.ubuntu.22_04.txt
src/util_impl_linux.h
xbyak_aarch64/xbyak_aarch64_version.h

This patch fixes SIGILL on Jetson.
https://github.com/fujitsu/xbyak_aarch64/issues/92

[linux] Fix SIGILL on Jetson

---

src/util_impl_linux.h

Check that result of `opendir()` is not `NULL`, before calling `readdir()` as later might crash if called with NULL argument, as one can see in https://godbolt.org/z/f3daEbPTx
This was the underlying source of crash in pytorch-2.1 on aarch64 platform when run inside the docker container, see https://github.com/pytorch/pytorch/issues/111695#issuecomment-1776324209

Fix crash in `getFilePathMaxTailNumPlus1`

---

src/util_impl_linux.h

`/sysfs` is inaccessible while running in AWS Lambda environment, or might be empty if executed inside container on Apple Silicon
Found while debugging https://github.com/pytorch/pytorch/issues/115482 to be cherry-picked into oneDNN later

Fallback to default while reading MIDR_EL1 sysfs

---

xbyak_aarch64/xbyak_aarch64_code_array.h
xbyak_aarch64/xbyak_aarch64_label.h

All jumps are performed relative to the current position, and the encoding is computed based upon jmpAddr - codeOffset. Which means that the encoding is unaffected by the absolute position of the code in memory. Thus, it is not necessary to treat the auto-grow mode differently, the encoding can always be computed eagerly.

simplify jump generation in auto-grow mode

---

.gitignore
src/xbyak_aarch64_impl.h
xbyak_aarch64/xbyak_aarch64_gen.h
xbyak_aarch64/xbyak_aarch64_meta_mnemonic.h

I have added meta mnemonics for logical operations with immediate (`and_imm`, `ands_imm`,`orr_imm`,`eor_imm`) and a function to check whether a value is a valid immediate for these kinds of instructions. I also fixed `align()` to not add padding if curr is already aligned, and `reset()` to reset the protection mode to RW so the code can be written to again.

Logical with Immediate meta-mnemonics and and bug fixes

---

xbyak_aarch64/xbyak_aarch64_gen.h
xbyak_aarch64/xbyak_aarch64_meta_mnemonic.h

@kawakami-k @burhanr13
I think it would be better to check tmp to avoid corrupting the values of src/dst. What do you think?

verify tmp not to destroy the values of dst/src

---

src/util_impl.cpp

Allows multiple flags to be checked in one call to `has` such as `has(XBYAK_AARCH64_HWCAP_SVE | XBYAK_AARCH64_HWCAP_ATOMIC)`.
This also includes an update to `isAtomicSupported` and
`isBf16Supported` to utilize the `has` function.

Update `has` to support multiple feature checks

---

sample/cpuinfo.cpp
src/util_impl_linux.h
src/util_impl_mac.h
src/util_impl_windows.h
xbyak_aarch64/xbyak_aarch64_util.h

CRC32 is an armv8.1 feature and has to be explicitly checked for before usage.

Add `crc` detection

---

sample/cpuinfo.cpp
src/util_impl_linux.h
src/util_impl_mac.h
src/util_impl_windows.h
xbyak_aarch64/xbyak_aarch64_util.h

Adds host-detection for support for `JSCVT` to properly guard usage of the `FJCVTZS` instruction.

Add `jscvt` detection
